apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    # Wyłączamy wymuszanie HTTPS na potrzeby testu (prościej)
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: moj-projekt.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app-svc
            port:
              number: 80
